language: java
sudo: required
dist: xenial

jdk:
  - openjdk8
  - openjdk11
  
install: true

script: mvn clean install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
  - $HOME/.m2
