language: java
sudo: required
dist: xenial

jdk:
  - openjdk8
  - openjdk11
  
install: true

script: 
  - ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
  - $HOME/.m2
